// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saidkpnglgsrotzkiybv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhaWRrcG5nbGdzcm90emtpeWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTE2ODksImV4cCI6MjA1MzEyNzY4OX0.EIWs4-xQEtoDT2ZYP7d76ckZvvoJ--EucNiK7rX__Ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);